mysql:
  host: 118.24.52.45
  username: root
  password: 6bm*h#yEZRuOZE$oMa0DyJlif234S6^O
  port: 30433
  database: shahaohuo
  showsql: true
  max-conns: 10
  min-conns: 2
s3:
  id: minio
  secret: F6JHNrx42weq0UIH1O
  endpoint: http://118.24.52.45:30434
  access-endpoint: http://118.24.52.45:30434
  region: china-chengdu-1
  disable-ssl: true
  s3-force-path-style: true
