mysql:
  host: rm-j6cl44qys35320hy1ro.mysql.rds.aliyuncs.com
  username: shahaohuo
  password: $Ar%%ZS!#$Zc6o4a^oxNhy
  port: 3306
  database: shahaohuo
  showsql: false
  max-conns: 16
  min-conns: 2
s3:
  id: LTAI4FyG9WqcAeTDm4xvNzUM
  secret: y1zpr3pkCSsQhPGtxWRXSfHGsnDW4i
  endpoint: https://shahaohuo.oss-cn-hongkong.aliyuncs.com
  access-endpoint: https://s3.hk.shahaohuo.com
  region: china-hongkong
  disable-ssl: false
  s3-force-path-style: true
