apiVersion: apps/v1
kind: Deployment
metadata:
  name: shahaohuo-server
  namespace: shahaohuo
  labels:
    shahaohuo-app: shahaohuo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      shahaohuo-app: shahaohuo-server
  template:
    metadata:
      labels:
        shahaohuo-app: shahaohuo-server
    spec:
      containers:
      - name: shahaohuo-server
        image: registry.cn-hongkong.aliyuncs.com/shahaohuo/server:latest
        imagePullPolicy: Always
#        restartPolicy: Always
        readinessProbe:
          httpGet:
            path: /status?from=k8s&type=readinessProbe
            port: http
          initialDelaySeconds: 30
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /status?from=k8s&type=livenessProbe
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 30
        resources:
          limits:
            memory: 64Mi
        env:
        - name: RESOURCES_PATH
          value: /opt/shahaohuo/resources
        - name: CONFIG_PATH
          value: /opt/shahaohuo/configs/prod.yaml
        - name: GIN_MODE
          value: release
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: shahaohuo-server-service
  labels:
    shahaohuo-app: shahaohuo-server
  namespace: shahaohuo
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    shahaohuo-app: shahaohuo-server

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: shahaohuo
  name: shaohaohuo.com
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    traefik.ingress.kubernetes.io/redirect-regex: "^https://www.(.*)"
    traefik.ingress.kubernetes.io/redirect-replacement: "https://$1"
    ingress.kubernetes.io/browser-xss-filter: "true"
spec:
  tls:
  - hosts:
    - shaohaohuo.com
    - www.shaohaohuo.com
    secretName: shahaohuo.com
  rules:
  - host: shahaohuo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: shahaohuo-server-service
          servicePort: 80
